name: Release Tag

on:
  release:
    types: [published]

jobs:
  Build:
    name: build release candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "I Only Run On RC Releases"
      - uses: mr-smithers-excellent/docker-build-push@v6.2
        name: Build & Push App Docker Image
        with:
          image: app
          registry: ghcr.io
          dockerfile: Dockerfile
          tags: ${{ github.ref_name }}
          addLatest: ${{ contains(github.ref_name, 'RC') }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

  ReuseableActionForReleaceCandidateTag:
    if: ${{ contains(github.ref_name, 'RC') }}
    name: deploy release candidate
    needs: [Build]
    strategy:
      matrix:
        host:
          - a
    uses: ./.github/workflows/ReuseableAction.yml
    with:
      host: ${{ matrix.host }}

  ReuseableActionForTag:
    if: ${{ !contains(github.ref_name, 'RC') }}
    name: deploy tag
    needs: [Build]
    strategy:
      matrix:
        host:
          - a
          - b
          - c
    uses: ./.github/workflows/ReuseableAction.yml
    with:
      host: ${{ matrix.host }}
