name: Release Tag

on:
  release:
    types: [published]

jobs:
  ReleaseCandidateTag:
    if: ${{ contains(github.ref_name, 'RC') }}
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4

      - run: echo "I Only Run On RC Releases"
      - uses: ./.github/workflows/ReuseableAction.yml

  ReleaseTag:
    if: ${{ !contains(github.ref_name, 'RC') }}
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4

      - run: echo "I Only Run On Releases"
      - uses: ./.github/workflows/ReuseableAction.yml
