name: Release Tag

on:
  release:
    types: [published]

jobs:
  ReleaseCandidateTag:
    if: ${{ contains(github.ref_name, 'RC') }}
    name: build release candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "I Only Run On RC Releases"

  ReuseableActionForReleaceCandidateTag:
    name: deploy release candidate
    needs: [ReleaseCandidateTag]
    strategy:
      matrix:
        host:
          - a
    uses: ./.github/workflows/ReuseableAction.yml
    with:
      host: ${{ matrix.host }}

  ReleaseTag:
    if: ${{ !contains(github.ref_name, 'RC') }}
    name: build tag
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - run: echo "I Only Run On Releases"

  ReuseableActionForTag:
    name: deploy tag
    needs: [ReleaseTag]
    strategy:
      matrix:
        host:
          - a
          - b
          - c
    uses: ./.github/workflows/ReuseableAction.yml
    with:
      host: ${{ matrix.host }}
